name: Auto-PR to master-ci

on:
  pull_request:
    types:
      - closed

jobs:
  auto-pr-to-master-ci:
    runs-on: ubuntu-latest
    
    steps:
    - name: create pull request
      run: gh pr create -B main -H release/2023.1.0 --title 'Merge release branch into main branch' --body 'Created by Github action'
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      # - name: Make changes to pull request
      #   run: date +%s > report.txt
        
      # - name: Auto Create Pull Request
      #   id: cpr
      #   uses: peter-evans/create-pull-request@v5
      #   with:
      #     # token: ${{ secrets.PAT }}
      #     commit-message: Update report
      #     # committer: GitHub <noreply@github.com>
      #     # author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
      #     # signoff: false
      #     branch: release/2023.1.0
      #     # delete-branch: true
          # title: '[Example] Update report'
          # body: |
            # Update report
            # - Updated with *today's* date
            # - Auto-generated by [create-pull-request][1]

            # [1]: https://github.com/peter-evans/create-pull-request
          # labels: |
            # report
            # automated pr
          # assignees: peter-evans
          # reviewers: peter-evans
          # team-reviewers: |
            # developers
            # qa-team
          # milestone: 1
          # draft: false
        
      # - name: Check outputs
      #   if: ${{ steps.cpr.outputs.pull-request-number }}
      #   run: |
      #     echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
      #     echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
  # auto-pr-to-master-ci:
  #   runs-on: ubuntu-latest

  #   steps:
  #   - name: Checkout Repository
  #     uses: actions/checkout@v2

  #   - name: Set Up Git
  #     run: |
  #       git config --global user.email "actions@github.com"
  #       git config --global user.name "GitHub Actions"

  #   - name: Determine Source and Target Branches
  #     run: |
  #       SOURCE_BRANCH=$(jq -r '.pull_request.head.ref' "$GITHUB_EVENT_PATH")
  #       TARGET_BRANCH="master-ci"

  #   - name: Create Auto-PR to master-ci
  #     run: |
  #       if [ "$SOURCE_BRANCH" == "release" ]; then
  #         # Define your new branch name
  #         new_branch="auto-pr-to-master-ci-$(date +%s)"
          
  #         # Create a new branch
  #         git checkout -b $new_branch
          
  #         # Make changes to the codebase, for example, updating a file
  #         echo "Auto-PR to master-ci change" >> example.txt

  #         # Commit changes
  #         git add .
  #         git commit -m "Auto-PR to master-ci commit"

  #         # Push the new branch to the repository
  #         git push origin $new_branch

  #         # Create a new pull request
  #         hub pull-request -m "Auto-PR to master-ci" -b $TARGET_BRANCH -h $new_branch || true
  #       fi
