name: Sync Branches

on:
  pull_request:
    types:
      - closed

jobs:
  sync-branches:
    if: ${{ (github.ref == 'release/2023.4.0') && (github.event.pull_request.merged == true) }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: create pull request
      run: gh pr create -B main -H release/2023.4.0 --title 'Merge release branch into main branch' --body 'Created by Github action'
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
